name: stronghold_ofw
description: Stronghold Software.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  carousel_slider: ^4.1.1
  cloud_firestore: ^3.1.17
  connectivity_plus: ^2.3.2
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  extended_image: ^6.2.1
  firebase_core: ^1.17.1
  firebase_storage: ^10.2.18
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.0
  fluttertoast: ^8.0.9
  freezed_annotation: ^2.0.3
  get_it: ^7.2.0
  hive: ^2.2.1
  image_picker: ^0.8.5+3
  image_picker_for_web: ^2.1.8
  intl: ^0.17.0
  json_annotation: ^4.5.0
  photo_view: ^0.14.0
  rxdart: ^0.27.4
  universal_html: ^2.0.8

dev_dependencies:
  build_runner: ^2.1.11
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.7
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3+1
  json_serializable: ^6.2.0

flutter_native_splash:
  image: lib/assets/logo.png
  color: "#FFFFFF"

flutter:
  uses-material-design: true

  assets:
    - lib/assets/
    - lib/
